name = "cloud-notepad"
main = "src/index.js"
compatibility_date = "2022-05-13"

kv_namespaces = [
  { binding = "NOTES", id = "6777e50862194dff81ca821ff1022512" },
  { binding = "SHARE", id = "09564b1c3ff642b4becb3966e6a36356" }
]